# Generated by Django 6.0.2 on 2026-03-07 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_instituicao_options_alter_rota_options_and_more'),
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condutor',
            options={'verbose_name': 'Condutor', 'verbose_name_plural': 'Condutores'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AlterField(
            model_name='condutor',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condutores', to='cadastros.secretaria'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='cadastros.secretaria'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_combustivel',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL_S10', 'Diesel S10'), ('DIESEL', 'Diesel Comum'), ('ETANOL', 'Etanol'), ('GNV', 'GNV')], max_length=50),
        ),
    ]
