# Generated by Django 6.0.2 on 2026-03-15 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_instituicao_options_alter_rota_options_and_more'),
        ('frota', '0002_alter_condutor_options_alter_veiculo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('condutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes', to='frota.condutor')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotacoes', to='cadastros.instituicao')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotacoes', to='cadastros.rota')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes', to='cadastros.secretaria')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotacoes', to='frota.veiculo')),
            ],
            options={
                'verbose_name': 'Lotação',
                'verbose_name_plural': 'Lotações',
                'ordering': ['-data', '-id'],
                'constraints': [models.UniqueConstraint(fields=('condutor', 'data'), name='unique_lotacao_por_condutor_e_data')],
            },
        ),
    ]
