# Generated by Django 6.0.2 on 2026-03-15 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_rota_v2'),
        ('frota', '0003_lotacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotacao',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='lotacao',
            name='secretaria',
        ),
        migrations.AddField(
            model_name='condutor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lotacao',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='rota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes', to='cadastros.rota'),
        ),
    ]
