# Generated by GPT-5.2 on 2026-03-15

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def create_default_superadmin(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")

    cpf = "99999999999"
    password = "admin"

    if Usuario.objects.filter(cpf=cpf).exists():
        return

    user = Usuario(
        cpf=cpf,
        password=make_password(password),
        is_staff=True,
        is_superuser=True,
        first_name="Super",
        last_name="Admin",
        can_write_cadastros=True,
        can_write_frota=True,
        can_create_guia_abastecimento=True,
        can_edit_guia_abastecimento=True,
        can_delete_guia_abastecimento=True,
    )
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_usuario_managers_remove_usuario_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="can_write_cadastros",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="can_write_frota",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="can_create_guia_abastecimento",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="can_edit_guia_abastecimento",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="can_delete_guia_abastecimento",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_default_superadmin, migrations.RunPython.noop),
    ]
