import type { FormSchema } from "../types/form"

export const guiaAbastecimentoFormSchema: FormSchema = {
  fields: [
    {
      name: "secretaria",
      label: "Secretaria",
      type: "select",
      required: true,
      endpoint: "cadastros/secretarias/",
      optionLabel: "sigla",
    },
    {
      name: "data_emissao",
      label: "Data",
      type: "date",
      required: true,
    },
    {
      name: "tipo_servico",
      label: "Tipo de Serviço",
      type: "select",
      required: true,
      options: [
        { label: "Caminhonete", value: "CAMINHONETE" },
        { label: "Ônibus", value: "ONIBUS" },
        { label: "Roçagem", value: "ROCAGEM" },
        { label: "Motocicleta", value: "MOTOCICLETA" },
        { label: "Barqueiro", value: "BARQUEIRO" },
        { label: "Carro", value: "CARRO" },
        { label: "Corote", value: "COROTE" },
      ],
    },
    {
      name: "condutor",
      label: "Condutor",
      type: "select",
      required: true,
      endpoint: "frota/condutores/",
      optionLabel: "nome_completo",
    },
    {
      name: "instituicao",
      label: "Instituição",
      type: "select",
      required: true,
      endpoint: "cadastros/instituicoes/",
      optionLabel: "nome",
      dependsOn: "secretaria",
      dependsOnParam: "secretaria",
    },
    {
      name: "rota",
      label: "Rota",
      type: "select",
      required: false,
      endpoint: "cadastros/rotas/",
      optionLabel: "descricao",
    },
    {
      name: "veiculo",
      label: "Veículo",
      type: "select",
      required: false,
      endpoint: "frota/veiculos/",
      optionLabel: "placa",
      dependsOn: "secretaria",
      dependsOnParam: "secretaria",
    },
    {
      name: "tipo_combustivel",
      label: "Tipo de Combustível",
      type: "select",
      required: true,
      options: [
        { label: "Gasolina", value: "GASOLINA" },
        { label: "Diesel Comum", value: "DIESEL" },
        { label: "Diesel S10", value: "DIESEL_S10" },
      ],
    },
    {
      name: "qtd_combustivel",
      label: "Quantidade de Combustível",
      type: "number",
      required: true,
    },
    {
      name: "qtd_oleo_lubrificante",
      label: "Quantidade de Óleo Lubrificante",
      type: "number",
      required: false,
    },
    {
      name: "hodometro",
      label: "Hodômetro",
      type: "number",
      required: false,
    },
    {
      name: "observacao",
      label: "Observação",
      type: "textarea",
      required: false,
    },
  ],
}
