# Generated by Django 6.0.2 on 2026-03-07 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
        migrations.AlterModelOptions(
            name='rota',
            options={'verbose_name': 'Rota', 'verbose_name_plural': 'Rotas'},
        ),
        migrations.AlterModelOptions(
            name='secretaria',
            options={'verbose_name': 'Secretaria', 'verbose_name_plural': 'Secretarias'},
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='rota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituicoes', to='cadastros.rota'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituicoes', to='cadastros.secretaria'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='tipo',
            field=models.CharField(choices=[('ESCOLA', 'Escola'), ('CRECHE', 'Creche'), ('UPA', 'UPA'), ('HOSPITAL', 'Hospital'), ('OUTRO', 'Outro')], max_length=100),
        ),
    ]
