# Generated by Django 6.0.2 on 2026-03-15 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_instituicao_options_alter_rota_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='rota',
        ),
        migrations.AddField(
            model_name='rota',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='consumo_medio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rota',
            name='detalhes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='distancia_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rota',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='cadastros.instituicao'),
        ),
        migrations.AddField(
            model_name='rota',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='cadastros.secretaria'),
        ),
    ]
