# Generated by Django 6.0.2 on 2026-03-04 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('frota', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField()),
                ('tipo_servico', models.CharField(max_length=100)),
                ('tipo_combustivel', models.CharField(max_length=50)),
                ('qtd_combustivel', models.DecimalField(decimal_places=3, max_digits=8)),
                ('qtd_oleo_lubrificante', models.DecimalField(decimal_places=3, max_digits=8)),
                ('hodometro', models.IntegerField()),
                ('observacao', models.TextField(blank=True)),
                ('condutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frota.condutor')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.instituicao')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.rota')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.secretaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frota.veiculo')),
            ],
        ),
    ]
