# Generated by Django 6.0.2 on 2026-03-07 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0001_initial'),
        ('cadastros', '0002_alter_instituicao_options_alter_rota_options_and_more'),
        ('frota', '0002_alter_condutor_options_alter_veiculo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiaabastecimento',
            options={'ordering': ['-data_emissao'], 'verbose_name': 'Guia de Abastecimento', 'verbose_name_plural': 'Guias de Abastecimento'},
        ),
        migrations.AlterField(
            model_name='guiaabastecimento',
            name='condutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='frota.condutor'),
        ),
        migrations.AlterField(
            model_name='guiaabastecimento',
            name='hodometro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guiaabastecimento',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='cadastros.instituicao'),
        ),
        migrations.AlterField(
            model_name='guiaabastecimento',
            name='qtd_oleo_lubrificante',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='guiaabastecimento',
            name='rota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='cadastros.rota'),
        ),
        migrations.AlterField(
            model_name='guiaabastecimento',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='cadastros.secretaria'),
        ),
        migrations.AlterField(
            model_name='guiaabastecimento',
            name='tipo_combustivel',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL_S10', 'Diesel S10'), ('DIESEL', 'Diesel Comum'), ('ETANOL', 'Etanol'), ('GNV', 'GNV')], max_length=50),
        ),
        migrations.AlterField(
            model_name='guiaabastecimento',
            name='tipo_servico',
            field=models.CharField(choices=[('CAMINHONETE', 'Caminhonete'), ('ONIBUS', 'Ônibus'), ('ROCAGEM', 'Roçagem'), ('MOTOCICLETA', 'Motocicleta'), ('BARQUEIRO', 'Barqueiro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='guiaabastecimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guiaabastecimento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='frota.veiculo'),
        ),
    ]
