# Generated by Django 6.0.2 on 2026-03-03 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0003_rota_secretaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastecimento.secretaria')),
            ],
        ),
    ]
