# Generated by Django 6.0.2 on 2026-03-03 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0004_condutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(max_length=4)),
                ('tipo_combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Diesel S10', 'Diesel S10')], max_length=20)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastecimento.secretaria')),
            ],
        ),
    ]
