# Generated by Django 6.0.2 on 2026-03-03 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0005_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastecimento.rota')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastecimento.secretaria')),
            ],
        ),
    ]
