# Generated by Django 6.0.2 on 2026-03-03 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0006_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('tipo_servico', models.CharField(choices=[('Caminhonete', 'Caminhonete'), ('Onibus', 'Onibus'), ('Motocicleta', 'Motocicleta'), ('Rocagem', 'Rocagem'), ('Barqueiro', 'Barqueiro')], max_length=20)),
                ('tipo_combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Diesel S10', 'Diesel S10')], max_length=20)),
                ('qtd_combustivel', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('qtd_oleo_lubrificante', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('hodometro', models.IntegerField(max_length=10)),
                ('obervacao', models.CharField(max_length=200, null=True)),
                ('condutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastecimento.condutor')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastecimento.instituicao')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastecimento.rota')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastecimento.secretaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastecimento.usuario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastecimento.veiculo')),
            ],
        ),
    ]
